language: ruby
sudo: false
script: 'script/cibuild'
cache: bundler
env:
  matrix:
    - SUITE=mysql
    - SUITE=pg
    - SUITE=sqlite3
    - SUITE=rubocop
rvm:
  - 2.1
matrix:
  fast_finish: true
  include:
    - rvm: 2.2
      env: SUITE=sqlite3
    - rvm: 2.3
notifications:
  email: false
services:
  - redis
bundler_args: --without deploy production debug --jobs 3 --retry 3
